[2025-07-25 11:10:10 +0000] [751307] [INFO] Starting gunicorn 23.0.0
[2025-07-25 11:10:10 +0000] [751307] [INFO] Listening at: http://127.0.0.1:8000 (751307)
[2025-07-25 11:10:10 +0000] [751307] [INFO] Using worker: sync
[2025-07-25 11:10:10 +0000] [751308] [INFO] Booting worker with pid: 751308
[2025-07-25 11:10:10 +0000] [751309] [INFO] Booting worker with pid: 751309
[2025-07-25 11:10:10 +0000] [751310] [INFO] Booting worker with pid: 751310
[2025-07-25 11:10:10 +0000] [751311] [INFO] Booting worker with pid: 751311
2025-07-25 11:10:13,390 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-07-25 11:10:13,390 - INFO - Added job "fetch_and_save_returns" to job store "default"
2025-07-25 11:10:13,390 - INFO - Scheduler started
2025-07-25 11:10:13,395 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-07-25 11:10:13,396 - INFO - Added job "fetch_and_save_returns" to job store "default"
2025-07-25 11:10:13,396 - INFO - Scheduler started
2025-07-25 11:10:13,462 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-07-25 11:10:13,463 - INFO - Added job "fetch_and_save_returns" to job store "default"
2025-07-25 11:10:13,463 - INFO - Scheduler started
2025-07-25 11:10:13,464 - INFO - Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-07-25 11:10:13,464 - INFO - Added job "fetch_and_save_returns" to job store "default"
2025-07-25 11:10:13,464 - INFO - Scheduler started
2025-07-25 11:10:21,717 - INFO - En eski 'Created' statüsündeki sipariş işleniyor.
2025-07-25 11:16:24,772 - ERROR - Log kaydedilemedi: (psycopg2.errors.UndefinedTable) relation "user_logs" does not exist
LINE 1: INSERT INTO user_logs (user_id, action, details, timestamp, ...
                    ^

[SQL: INSERT INTO user_logs (user_id, action, details, timestamp, ip_address, page_url, status_code) VALUES (%(user_id)s, %(action)s, %(details)s, %(timestamp)s, %(ip_address)s, %(page_url)s, %(status_code)s) RETURNING user_logs.id]
[parameters: {'user_id': 21, 'action': 'PAGE_VIEW: index', 'details': '{"İşlem": "Sayfa Görüntüleme", "Sayfa": "index", "Kullanıcı Rolü": "Yönetici", "Tarayıcı": "Bilinmiyor", "İşletim Sistemi": "Bilinmiyor", "Gelinen Sayfa": "Doğrudan Giriş", "Path": "/", "Endpoint": "index"}', 'timestamp': datetime.datetime(2025, 7, 25, 11, 16, 24, 771089), 'ip_address': '127.0.0.1', 'page_url': 'https://gullupanel.com/', 'status_code': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-25 11:16:24,925 - ERROR - Log kaydedilemedi: (psycopg2.errors.UndefinedTable) relation "user_logs" does not exist
LINE 1: INSERT INTO user_logs (user_id, action, details, timestamp, ...
                    ^

[SQL: INSERT INTO user_logs (user_id, action, details, timestamp, ip_address, page_url, status_code) VALUES (%(user_id)s, %(action)s, %(details)s, %(timestamp)s, %(ip_address)s, %(page_url)s, %(status_code)s) RETURNING user_logs.id]
[parameters: {'user_id': 21, 'action': 'PAGE_VIEW: home.home', 'details': '{"İşlem": "Sayfa Görüntüleme", "Sayfa": "home.home", "Kullanıcı Rolü": "Yönetici", "Tarayıcı": "Bilinmiyor", "İşletim Sistemi": "Bilinmiyor", "Gelinen Sayfa": "Doğrudan Giriş", "Path": "/anasayfa", "Endpoint": "home.home"}', 'timestamp': datetime.datetime(2025, 7, 25, 11, 16, 24, 923868), 'ip_address': '127.0.0.1', 'page_url': 'https://gullupanel.com/anasayfa', 'status_code': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-25 11:16:24,936 - ERROR - Bir hata oluştu: (psycopg2.errors.UndefinedTable) relation "orders_created" does not exist
LINE 2: FROM orders_created ORDER BY orders_created.order_date 
             ^

[SQL: SELECT orders_created.id AS orders_created_id, orders_created.order_number AS orders_created_order_number, orders_created.order_date AS orders_created_order_date, orders_created.status AS orders_created_status, orders_created.customer_id AS orders_created_customer_id, orders_created.customer_name AS orders_created_customer_name, orders_created.customer_surname AS orders_created_customer_surname, orders_created.customer_address AS orders_created_customer_address, orders_created.merchant_sku AS orders_created_merchant_sku, orders_created.product_barcode AS orders_created_product_barcode, orders_created.product_name AS orders_created_product_name, orders_created.product_code AS orders_created_product_code, orders_created.product_size AS orders_created_product_size, orders_created.product_color AS orders_created_product_color, orders_created.product_main_id AS orders_created_product_main_id, orders_created."stockCode" AS "orders_created_stockCode", orders_created.line_id AS orders_created_line_id, orders_created.details AS orders_created_details, orders_created.quantity AS orders_created_quantity, orders_created.amount AS orders_created_amount, orders_created.discount AS orders_created_discount, orders_created.gross_amount AS orders_created_gross_amount, orders_created.tax_amount AS orders_created_tax_amount, orders_created.vat_base_amount AS orders_created_vat_base_amount, orders_created.commission AS orders_created_commission, orders_created.currency_code AS orders_created_currency_code, orders_created.product_cost_total AS orders_created_product_cost_total, orders_created.package_number AS orders_created_package_number, orders_created.shipment_package_id AS orders_created_shipment_package_id, orders_created.shipping_barcode AS orders_created_shipping_barcode, orders_created.cargo_tracking_number AS orders_created_cargo_tracking_number, orders_created.cargo_provider_name AS orders_created_cargo_provider_name, orders_created.cargo_tracking_link AS orders_created_cargo_tracking_link, orders_created.shipment_package_status AS orders_created_shipment_package_status, orders_created.origin_shipment_date AS orders_created_origin_shipment_date, orders_created.estimated_delivery_start AS orders_created_estimated_delivery_start, orders_created.estimated_delivery_end AS orders_created_estimated_delivery_end, orders_created.agreed_delivery_date AS orders_created_agreed_delivery_date, orders_created.last_modified_date AS orders_created_last_modified_date, orders_created.match_status AS orders_created_match_status, orders_created.images AS orders_created_images, orders_created.product_model_code AS orders_created_product_model_code, orders_created.created_at AS orders_created_created_at, orders_created.updated_at AS orders_created_updated_at 
FROM orders_created ORDER BY orders_created.order_date 
 LIMIT %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "orders_created" does not exist
LINE 2: FROM orders_created ORDER BY orders_created.order_date 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/musir/gullupanel/yeni/home.py", line 31, in get_home
    oldest_order = OrderCreated.query.order_by(OrderCreated.order_date).first()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2728, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "orders_created" does not exist
LINE 2: FROM orders_created ORDER BY orders_created.order_date 
             ^

[SQL: SELECT orders_created.id AS orders_created_id, orders_created.order_number AS orders_created_order_number, orders_created.order_date AS orders_created_order_date, orders_created.status AS orders_created_status, orders_created.customer_id AS orders_created_customer_id, orders_created.customer_name AS orders_created_customer_name, orders_created.customer_surname AS orders_created_customer_surname, orders_created.customer_address AS orders_created_customer_address, orders_created.merchant_sku AS orders_created_merchant_sku, orders_created.product_barcode AS orders_created_product_barcode, orders_created.product_name AS orders_created_product_name, orders_created.product_code AS orders_created_product_code, orders_created.product_size AS orders_created_product_size, orders_created.product_color AS orders_created_product_color, orders_created.product_main_id AS orders_created_product_main_id, orders_created."stockCode" AS "orders_created_stockCode", orders_created.line_id AS orders_created_line_id, orders_created.details AS orders_created_details, orders_created.quantity AS orders_created_quantity, orders_created.amount AS orders_created_amount, orders_created.discount AS orders_created_discount, orders_created.gross_amount AS orders_created_gross_amount, orders_created.tax_amount AS orders_created_tax_amount, orders_created.vat_base_amount AS orders_created_vat_base_amount, orders_created.commission AS orders_created_commission, orders_created.currency_code AS orders_created_currency_code, orders_created.product_cost_total AS orders_created_product_cost_total, orders_created.package_number AS orders_created_package_number, orders_created.shipment_package_id AS orders_created_shipment_package_id, orders_created.shipping_barcode AS orders_created_shipping_barcode, orders_created.cargo_tracking_number AS orders_created_cargo_tracking_number, orders_created.cargo_provider_name AS orders_created_cargo_provider_name, orders_created.cargo_tracking_link AS orders_created_cargo_tracking_link, orders_created.shipment_package_status AS orders_created_shipment_package_status, orders_created.origin_shipment_date AS orders_created_origin_shipment_date, orders_created.estimated_delivery_start AS orders_created_estimated_delivery_start, orders_created.estimated_delivery_end AS orders_created_estimated_delivery_end, orders_created.agreed_delivery_date AS orders_created_agreed_delivery_date, orders_created.last_modified_date AS orders_created_last_modified_date, orders_created.match_status AS orders_created_match_status, orders_created.images AS orders_created_images, orders_created.product_model_code AS orders_created_product_model_code, orders_created.created_at AS orders_created_created_at, orders_created.updated_at AS orders_created_updated_at 
FROM orders_created ORDER BY orders_created.order_date 
 LIMIT %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-25 11:16:29,868 - ERROR - Log kaydedilemedi: (psycopg2.errors.UndefinedTable) relation "user_logs" does not exist
LINE 1: INSERT INTO user_logs (user_id, action, details, timestamp, ...
                    ^

[SQL: INSERT INTO user_logs (user_id, action, details, timestamp, ip_address, page_url, status_code) VALUES (%(user_id)s, %(action)s, %(details)s, %(timestamp)s, %(ip_address)s, %(page_url)s, %(status_code)s) RETURNING user_logs.id]
[parameters: {'user_id': 21, 'action': 'PAGE_VIEW: degisim.degisim_talep', 'details': '{"İşlem": "Sayfa Görüntüleme", "Sayfa": "degisim.degisim_talep", "Kullanıcı Rolü": "Yönetici", "Tarayıcı": "Bilinmiyor", "İşletim Sistemi": "Bilinmiyor", "Gelinen Sayfa": "Doğrudan Giriş", "Path": "/degisim_talep", "Endpoint": "degisim.degisim_talep"}', 'timestamp': datetime.datetime(2025, 7, 25, 11, 16, 29, 867184), 'ip_address': '127.0.0.1', 'page_url': 'https://gullupanel.com/degisim_talep', 'status_code': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2025-07-25 11:16:29 +0000] [751310] [ERROR] Error handling request /degisim_talep
Traceback (most recent call last):
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "degisim" does not exist
LINE 2: FROM degisim ORDER BY degisim.degisim_tarihi DESC 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/yeni/degisim.py", line 199, in degisim_talep
    pagination = query.paginate(page=page, per_page=per_page, error_out=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_sqlalchemy/query.py", line 98, in paginate
    return QueryPagination(
           ^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_sqlalchemy/pagination.py", line 72, in __init__
    items = self._query_items()
            ^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_sqlalchemy/pagination.py", line 358, in _query_items
    out = query.limit(self.per_page).offset(self._query_offset).all()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "degisim" does not exist
LINE 2: FROM degisim ORDER BY degisim.degisim_tarihi DESC 
             ^

[SQL: SELECT degisim.id AS degisim_id, degisim.degisim_no AS degisim_degisim_no, degisim.siparis_no AS degisim_siparis_no, degisim.ad AS degisim_ad, degisim.soyad AS degisim_soyad, degisim.adres AS degisim_adres, degisim.telefon_no AS degisim_telefon_no, degisim.degisim_tarihi AS degisim_degisim_tarihi, degisim.degisim_durumu AS degisim_degisim_durumu, degisim.kargo_kodu AS degisim_kargo_kodu, degisim.degisim_nedeni AS degisim_degisim_nedeni, degisim.urunler_json AS degisim_urunler_json 
FROM degisim ORDER BY degisim.degisim_tarihi DESC 
 LIMIT %(param_1)s OFFSET %(param_2)s]
[parameters: {'param_1': 12, 'param_2': 0}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-25 11:16:39,672 - ERROR - Log kaydedilemedi: (psycopg2.errors.UndefinedTable) relation "user_logs" does not exist
LINE 1: INSERT INTO user_logs (user_id, action, details, timestamp, ...
                    ^

[SQL: INSERT INTO user_logs (user_id, action, details, timestamp, ip_address, page_url, status_code) VALUES (%(user_id)s, %(action)s, %(details)s, %(timestamp)s, %(ip_address)s, %(page_url)s, %(status_code)s) RETURNING user_logs.id]
[parameters: {'user_id': 21, 'action': 'PAGE_VIEW: index', 'details': '{"İşlem": "Sayfa Görüntüleme", "Sayfa": "index", "Kullanıcı Rolü": "Yönetici", "Tarayıcı": "Bilinmiyor", "İşletim Sistemi": "Bilinmiyor", "Gelinen Sayfa": "Doğrudan Giriş", "Path": "/", "Endpoint": "index"}', 'timestamp': datetime.datetime(2025, 7, 25, 11, 16, 39, 671555), 'ip_address': '127.0.0.1', 'page_url': 'https://gullupanel.com/', 'status_code': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-25 11:16:40,774 - ERROR - Log kaydedilemedi: (psycopg2.errors.UndefinedTable) relation "user_logs" does not exist
LINE 1: INSERT INTO user_logs (user_id, action, details, timestamp, ...
                    ^

[SQL: INSERT INTO user_logs (user_id, action, details, timestamp, ip_address, page_url, status_code) VALUES (%(user_id)s, %(action)s, %(details)s, %(timestamp)s, %(ip_address)s, %(page_url)s, %(status_code)s) RETURNING user_logs.id]
[parameters: {'user_id': 21, 'action': 'PAGE_VIEW: home.home', 'details': '{"İşlem": "Sayfa Görüntüleme", "Sayfa": "home.home", "Kullanıcı Rolü": "Yönetici", "Tarayıcı": "Bilinmiyor", "İşletim Sistemi": "Bilinmiyor", "Gelinen Sayfa": "Doğrudan Giriş", "Path": "/anasayfa", "Endpoint": "home.home"}', 'timestamp': datetime.datetime(2025, 7, 25, 11, 16, 40, 772719), 'ip_address': '127.0.0.1', 'page_url': 'https://gullupanel.com/anasayfa', 'status_code': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-25 11:16:40,776 - ERROR - Bir hata oluştu: (psycopg2.errors.UndefinedTable) relation "orders_created" does not exist
LINE 2: FROM orders_created ORDER BY orders_created.order_date 
             ^

[SQL: SELECT orders_created.id AS orders_created_id, orders_created.order_number AS orders_created_order_number, orders_created.order_date AS orders_created_order_date, orders_created.status AS orders_created_status, orders_created.customer_id AS orders_created_customer_id, orders_created.customer_name AS orders_created_customer_name, orders_created.customer_surname AS orders_created_customer_surname, orders_created.customer_address AS orders_created_customer_address, orders_created.merchant_sku AS orders_created_merchant_sku, orders_created.product_barcode AS orders_created_product_barcode, orders_created.product_name AS orders_created_product_name, orders_created.product_code AS orders_created_product_code, orders_created.product_size AS orders_created_product_size, orders_created.product_color AS orders_created_product_color, orders_created.product_main_id AS orders_created_product_main_id, orders_created."stockCode" AS "orders_created_stockCode", orders_created.line_id AS orders_created_line_id, orders_created.details AS orders_created_details, orders_created.quantity AS orders_created_quantity, orders_created.amount AS orders_created_amount, orders_created.discount AS orders_created_discount, orders_created.gross_amount AS orders_created_gross_amount, orders_created.tax_amount AS orders_created_tax_amount, orders_created.vat_base_amount AS orders_created_vat_base_amount, orders_created.commission AS orders_created_commission, orders_created.currency_code AS orders_created_currency_code, orders_created.product_cost_total AS orders_created_product_cost_total, orders_created.package_number AS orders_created_package_number, orders_created.shipment_package_id AS orders_created_shipment_package_id, orders_created.shipping_barcode AS orders_created_shipping_barcode, orders_created.cargo_tracking_number AS orders_created_cargo_tracking_number, orders_created.cargo_provider_name AS orders_created_cargo_provider_name, orders_created.cargo_tracking_link AS orders_created_cargo_tracking_link, orders_created.shipment_package_status AS orders_created_shipment_package_status, orders_created.origin_shipment_date AS orders_created_origin_shipment_date, orders_created.estimated_delivery_start AS orders_created_estimated_delivery_start, orders_created.estimated_delivery_end AS orders_created_estimated_delivery_end, orders_created.agreed_delivery_date AS orders_created_agreed_delivery_date, orders_created.last_modified_date AS orders_created_last_modified_date, orders_created.match_status AS orders_created_match_status, orders_created.images AS orders_created_images, orders_created.product_model_code AS orders_created_product_model_code, orders_created.created_at AS orders_created_created_at, orders_created.updated_at AS orders_created_updated_at 
FROM orders_created ORDER BY orders_created.order_date 
 LIMIT %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
Traceback (most recent call last):
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "orders_created" does not exist
LINE 2: FROM orders_created ORDER BY orders_created.order_date 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/musir/gullupanel/yeni/home.py", line 31, in get_home
    oldest_order = OrderCreated.query.order_by(OrderCreated.order_date).first()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2728, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "orders_created" does not exist
LINE 2: FROM orders_created ORDER BY orders_created.order_date 
             ^

[SQL: SELECT orders_created.id AS orders_created_id, orders_created.order_number AS orders_created_order_number, orders_created.order_date AS orders_created_order_date, orders_created.status AS orders_created_status, orders_created.customer_id AS orders_created_customer_id, orders_created.customer_name AS orders_created_customer_name, orders_created.customer_surname AS orders_created_customer_surname, orders_created.customer_address AS orders_created_customer_address, orders_created.merchant_sku AS orders_created_merchant_sku, orders_created.product_barcode AS orders_created_product_barcode, orders_created.product_name AS orders_created_product_name, orders_created.product_code AS orders_created_product_code, orders_created.product_size AS orders_created_product_size, orders_created.product_color AS orders_created_product_color, orders_created.product_main_id AS orders_created_product_main_id, orders_created."stockCode" AS "orders_created_stockCode", orders_created.line_id AS orders_created_line_id, orders_created.details AS orders_created_details, orders_created.quantity AS orders_created_quantity, orders_created.amount AS orders_created_amount, orders_created.discount AS orders_created_discount, orders_created.gross_amount AS orders_created_gross_amount, orders_created.tax_amount AS orders_created_tax_amount, orders_created.vat_base_amount AS orders_created_vat_base_amount, orders_created.commission AS orders_created_commission, orders_created.currency_code AS orders_created_currency_code, orders_created.product_cost_total AS orders_created_product_cost_total, orders_created.package_number AS orders_created_package_number, orders_created.shipment_package_id AS orders_created_shipment_package_id, orders_created.shipping_barcode AS orders_created_shipping_barcode, orders_created.cargo_tracking_number AS orders_created_cargo_tracking_number, orders_created.cargo_provider_name AS orders_created_cargo_provider_name, orders_created.cargo_tracking_link AS orders_created_cargo_tracking_link, orders_created.shipment_package_status AS orders_created_shipment_package_status, orders_created.origin_shipment_date AS orders_created_origin_shipment_date, orders_created.estimated_delivery_start AS orders_created_estimated_delivery_start, orders_created.estimated_delivery_end AS orders_created_estimated_delivery_end, orders_created.agreed_delivery_date AS orders_created_agreed_delivery_date, orders_created.last_modified_date AS orders_created_last_modified_date, orders_created.match_status AS orders_created_match_status, orders_created.images AS orders_created_images, orders_created.product_model_code AS orders_created_product_model_code, orders_created.created_at AS orders_created_created_at, orders_created.updated_at AS orders_created_updated_at 
FROM orders_created ORDER BY orders_created.order_date 
 LIMIT %(param_1)s]
[parameters: {'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-07-25 11:16:49,972 - ERROR - Log kaydedilemedi: (psycopg2.errors.UndefinedTable) relation "user_logs" does not exist
LINE 1: INSERT INTO user_logs (user_id, action, details, timestamp, ...
                    ^

[SQL: INSERT INTO user_logs (user_id, action, details, timestamp, ip_address, page_url, status_code) VALUES (%(user_id)s, %(action)s, %(details)s, %(timestamp)s, %(ip_address)s, %(page_url)s, %(status_code)s) RETURNING user_logs.id]
[parameters: {'user_id': 21, 'action': 'PAGE_VIEW: degisim.degisim_talep', 'details': '{"İşlem": "Sayfa Görüntüleme", "Sayfa": "degisim.degisim_talep", "Kullanıcı Rolü": "Yönetici", "Tarayıcı": "Bilinmiyor", "İşletim Sistemi": "Bilinmiyor", "Gelinen Sayfa": "Doğrudan Giriş", "Path": "/degisim_talep", "Endpoint": "degisim.degisim_talep"}', 'timestamp': datetime.datetime(2025, 7, 25, 11, 16, 49, 972048), 'ip_address': '127.0.0.1', 'page_url': 'https://gullupanel.com/degisim_talep', 'status_code': None}]
(Background on this error at: https://sqlalche.me/e/20/f405)
[2025-07-25 11:16:49 +0000] [751310] [ERROR] Error handling request /degisim_talep
Traceback (most recent call last):
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "degisim" does not exist
LINE 2: FROM degisim ORDER BY degisim.degisim_tarihi DESC 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/yeni/degisim.py", line 199, in degisim_talep
    pagination = query.paginate(page=page, per_page=per_page, error_out=False)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_sqlalchemy/query.py", line 98, in paginate
    return QueryPagination(
           ^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_sqlalchemy/pagination.py", line 72, in __init__
    items = self._query_items()
            ^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/flask_sqlalchemy/pagination.py", line 358, in _query_items
    out = query.limit(self.per_page).offset(self._query_offset).all()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/musir/gullupanel/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "degisim" does not exist
LINE 2: FROM degisim ORDER BY degisim.degisim_tarihi DESC 
             ^

[SQL: SELECT degisim.id AS degisim_id, degisim.degisim_no AS degisim_degisim_no, degisim.siparis_no AS degisim_siparis_no, degisim.ad AS degisim_ad, degisim.soyad AS degisim_soyad, degisim.adres AS degisim_adres, degisim.telefon_no AS degisim_telefon_no, degisim.degisim_tarihi AS degisim_degisim_tarihi, degisim.degisim_durumu AS degisim_degisim_durumu, degisim.kargo_kodu AS degisim_kargo_kodu, degisim.degisim_nedeni AS degisim_degisim_nedeni, degisim.urunler_json AS degisim_urunler_json 
FROM degisim ORDER BY degisim.degisim_tarihi DESC 
 LIMIT %(param_1)s OFFSET %(param_2)s]
[parameters: {'param_1': 12, 'param_2': 0}]
(Background on this error at: https://sqlalche.me/e/20/f405)
